#!/bin/bash

#copia y corta archivo sac 
#Programa para archivos sac de 24 hr en SEAGATEB de la RED

IN_DIR=$(pwd)
OUT_DIR=$(pwd)'/data'

mkdir $OUT_DIR

rm ${OUT_DIR}/*.sac_deconv
rm ${OUT_DIR}/*.sac_rot
rm ${OUT_DIR}/*.sac


rm ${OUT_DIR}/stat.list
declare -a station

station[0]=NE75
station[1]=NE81
station[2]=NE82
station[3]=NE83
station[4]=NE84
station[5]=NE74
station[6]=NE80
station[7]=NE76
station[8]=NE77
station[9]=NE79

year=$1
month=$2
day=$3

hour=$4
min=$5
sec=$6

DeltaT=$7



#read  T0 <<< `./calc $hour*60*60+$min*60+$sec`
T0=0

read  T1 <<< `calc $T0+$DeltaT`

echo $T0 $T1



declare -a splited_name

declare -a files

cont=0

#find the sac file corresponding to the given hour and cut it 

for  kk in 2 3 8 9
do


  IFS=' '  read  jday <<< `julian_day $year $month $day`

  echo Julian day: $jday




  ls *.${station[$kk]}.*$year.$jday* >tmp

  for sac_file in `cat tmp`
  do
#    IFS='.'  read -ra splited_name <<< $sac_file
    
    splited_name=($(echo $sac_file | tr "." "\n"))

    echo ${splited_name[@]}



name_cp=$year.$jday.$hour.$min.$sec.${splited_name[1]}.${splited_name[2]}.sac
     echo name_cp $name_cp

echo ${splited_name[1]}_${splited_name[2]} >> $OUT_DIR/stat.list


sac << eof
 
      setbb name "$sac_file"
      setbb name_cp "${name_cp}"

      setbb time0  "$T0"
      setbb time1  "$T1"

      getbb name
      getbb name_cp
      getbb time0
      getbb time1

      cut  %time0 %time1
      
      read %name
      synchronize
      taper

      write %name_cp

      quit
      quit

eof


  mv ${name_cp} $OUT_DIR/${name_cp}




  done



done 







